mysite/face/urls.py
from django.urls import path

from . import views

app_name = 'face'
urlpatterns = [
    # ex: /face/
    path('', views.index, name='index'),
    # ex: /face/5/
    path('<int:department_id>/', views.detail, name='detail'),

    path('register/', views.register, name='register'),

    path('<int:people_id>/info/', views.info, name='info'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('polls/', include('polls.urls')),
    path('face/', include('face.urls')),
    path('face_detector/', include('face_detector.urls')),
    path('admin/', admin.site.urls),
]

mysite/face/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    department_name = models.CharField(max_length=200)

    def __str__(self):
        return self.department_name

class People(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

mysite/face/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.urls.base import reverse

from face.models import Department, People

# Create your views here.
# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")


def index(request):
    department_list = Department.objects.all()
    context = {'department_list': department_list}
    return render(request, "face/index.html", context)


def detail(request, department_id):
    return HttpResponse("You're looking at deparment %s." % department_id)


def register(request):
    name = request.POST['name']
    departmentId = request.POST['department_id']
    people = People(name=name, department_id=departmentId)
    people.save()

    return HttpResponseRedirect(reverse('face:info', args=(people.id,)))


def info(request, people_id):
    people = get_object_or_404(People, pk=people_id)
    try:        
        department = Department.objects.get(id=people.department_id)
    except(KeyError, People.DoesNotExist):
        print("================================================")
        # Redisplay the question voting form.
        return render(request, 'face/info.html', {
            'error_message': "This user is not exist",
        })
    else:
        return render(request, 'face/info.html', {'people': people, 'department': department})

mysite/face/templates/face/index.html
{% if department_list %}
<ul>
    {% for department in department_list %}
    <li><a href="{% url 'face:detail' department.id %}"> {{department.department_name}}</a></li>
    {% endfor %}
</ul>
{% endif %}

<div style="width: 570px;">
    <form action="{% url 'face:register'  %}" method="post">
        {% csrf_token %}

        <div style="height: 30px;">
            <div class="cont-wp">Name: </div>
            <div class="cont-wp"><input type="text" name="name" /></div>
        </div>
        <div>
            <div class="cont-wp">Department: </div>
            <div class="cont-wp">
                <select id="department_id" name="department_id" class="form-control">
                    <option value="" selected>Please select a department</option>
                    {% for department in department_list %}
                    <option value="{{ department.id }}">{{ department.department_name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div><input type="submit" value="Register"></div>        
    </form>
</div>

<style>
    .cont-wp {
        display: inline-block;
        width: 49%;
    }
</style>

mysite/face/templates/face/info.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div>
    <div style="height: 30px;">
        <div class="cont-wp">Id: </div>
        <div class="cont-wp">{{ people.id }}</div>
    </div>
    <div style="height: 30px;">
        <div class="cont-wp">Name: </div>
        <div class="cont-wp">{{ people.name }}</div>
    </div>
    <div style="height: 30px;">
        <div class="cont-wp">Department: </div>
        <div class="cont-wp">{{department.department_name}}</div>
    </div>
</div>

<style>
    .cont-wp {
        display: inline-block;
        width: 200px;
    }
</style>